project:
  type: website
  output-dir: static

website:
  title: "leakybrain"
  sidebar:
    contents: auto
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/ekholme/leakybrain
      # - href: index.qmd
      #   text: Home
      # - about.qmd
      # - section: "Go"
      #   contents:
      #     - Go
      # - section: "R"
      #   contents:
      #     - R
      # - section: "Julia"
      #   contents:
      #     - Julia
      # - section: "Stats"
      #   contents:
      #     - auto: Stats


format:
  html:
    theme: simplex
    css: styles.css
    toc: true

#freeze computational output
# see https://quarto.org/docs/projects/code-execution.html#freeze
freeze: auto


