project:
  type: website
  output-dir: static

website:
  title: "leakybrain"
  sidebar:
    contents: auto
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/ekholme/leakybrain
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

#freeze computational output
# see https://quarto.org/docs/projects/code-execution.html#freeze
freeze: auto


